### PR TITLE
Some QOL changes.

### PR DESCRIPTION
**Pull request by ghost**
- Color support for ban messages
- Delay login attempts during banlist initialization instead of just kicking them
  1. Kicks the player if the plugin gets disabled mid-initialization
- Prettied up default ban message (also fixed the null as the UBL changed one of the field names)

### CODE REVIEW

**Comment by XHawk87** [comment]
Hi D4mnX. Thanks for your contribution!

Before I can merge, we'll need to make this backwards-compatible for earlier versions of Bukkit. The ChatColor.translateAlternateColorCodes was added in 1.7.9-R0.2, and it would be a shame to lose support for 1.7.2 and earlier just for this convenience method.

You can find the source for this method [here](https://github.com/Bukkit/Bukkit/commit/c4c523723226ba288758079fe10a30af0ab0c332). If we include that in AutoUBL it will allow earlier servers to make use of it too.

Also, I'll need to test it before it can be approved, though if you send me evidence of testing (screenshots and console logs) showing these changes working on 1.7.2 or earlier and 1.7.9 or later, then I'll be able to merge it right away.

**Comment by ghost** [comment]
Oh sorry, I didn't expect you to reply early at all, as your reddit profile is pretty much dead, haha.

Chatcolor.translateAlternateColorCodes has been in Bukkit since 1.2.4-R1.0, according to [this commit.](https://github.com/Bukkit/Bukkit/commit/c4c523723226ba288758079fe10a30af0ab0c332) That shouldn't be an issue, unless you are aiming for compability even below that (which might be a pretty huge task).

I've tested the changes myself, I did not notice any issues. During testing, I changed the banlist URL to [a testing spreadsheet](https://docs.google.com/spreadsheets/d/1i7q1R_Us7FyVFDbE0q08z2_BJyB4lusXTPc7ZNHlsNc/edit#gid=0) with my own name on it, resulting in me not being able to join my server. I can attach a screenshot of the ban message if you want (although I'm not sure if it's 100% needed).

What I did not test is what happens if a player is connecting while AutoUBL was reloaded mid-initialization ([which should result in the player being kicked](https://github.com/D4mnX/AutoUBL/commit/894fb385a1294a47117719c888ede85f5cc7391a))... I'll do that right now.

EDIT: Testing is done. Lsperlo was nice and added me temporarly (I was too lazy to populate a test spreadsheet with gazillions of lines). Logs can be found [here](http://pastebin.com/raw.php?i=TYa5prfS), the ban reason was amazing though, 10/10.

(No, I don't mind my IP being shared publicly, I have a dynamic IP address.)

As you may be able to see, your plugin doesn't check if it's still enabled once the data is parsed. I can include a fix for this in the PR if you wish.

**Comment by XHawk87** [comment]
Yeh, not a lot of time for reddit atm, lots of work to do!

You are correct, my mistake. There shouldn't be any need to make this compatible with earlier than 1.2.4, and if there is we'd need a more elegant solution than importing sections of code.

LOL @ at the ban reason. This looks fine to me.

If you want to include that fix too, I'd be happy to wait before merging, otherwise I'll go ahead.

**Comment by ghost** [comment]
Alright I'll quickly work on that fix. I'll comment again when it's done and tested.

**Comment by ghost** [comment]
Logs for [9ceab6](https://github.com/D4mnX/AutoUBL/commit/9ceabd68807ebc4a95de5a15543d1d4b5b413c99): http://pastebin.com/raw.php?i=4A2tBCnN

Seems to do the trick.

**Comment by XHawk87** [comment]
That all looks good, merging now. Thanks again for your contribution!

**Comment by ghost** [comment]
No problem. Just wondering, are you planning to release this to the UHC community, or do you want to work on some other stuff first?

**Comment by XHawk87** [comment]
There have been no other issues reported or features requested, so I'll try to publish it sometime today. If you have a dev.bukkit.org account, I can add you as a contributor.

**Comment by ghost** [comment]
I don't think I have a account over there, but thanks for the offer \o/

**Comment by XHawk87** [comment]
I have posted the update now, just waiting on BukkitDev moderation: http://dev.bukkit.org/bukkit-plugins/autoubl/files/7-auto-ubl-v0-2-1-dev/

**Pull request merged**
